name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

jobs:
  build_push_image:
<<<<<<< HEAD
    runs-on: ubuntu-latest
=======
    runs-on: ubuntu-20.04
>>>>>>> 39a9e1ef3ad336e1aae29b6396b13234caad1d57

    steps:
      - uses: actions/checkout@v2

<<<<<<< HEAD
      - name: Build and push staging image
        uses: docker/build-push-action@v1.1.1
        with:
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}
          registry: ${{ secrets.ACR_NAME }}
          repository: contoso-website
          tags: latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image

    steps:
      - uses: actions/checkout@v2

      - name: Install Helm
        uses: Azure/setup-helm@v1
        with:
          version: v3.3.1

      - name: Get AKS Credentials
        uses: Azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          # Resource Group Name
          resource-group: mslearn-gh-pipelines-29740
          # AKS Cluster Name
          cluster-name: contoso-video

      - name: Run Helm Deploy
        run: |
          helm upgrade \
            --install \
            --create-namespace \
            --atomic \
            --wait \
            --namespace staging \
            contoso-website \
            ./kubernetes/contoso-website \
            --set image.repository=${{ secrets.ACR_NAME }} \
            --set dns.name=${{ secrets.DNS_NAME }} 
=======
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/contoso-website:latest
          push: true
>>>>>>> 39a9e1ef3ad336e1aae29b6396b13234caad1d57
